### ISSUE TITLE
Event sourcing draft

### ISSUE THREAD

**Issue by kjellm** [kjellm/kjellm.github.com#1]

**Comment by thhermansen** [comment]
* Hvorfor har vi `InstanceMethods` og include modulen (eks `CommandHandler` med flere).
  * Tror jeg fant [svaret](https://gist.github.com/kjellm/ec8fbaac65a28d67f17d941cc454f0f1#file-crud-rb-L50-L72).
* Inline docs av klassene og hva deres rolle/ansvar er kunne vært fint.
* Hvordan håndtere Index-er: Garantere unike verdier ut over ID. Kanskje en annen konstruksjon får det ansvaret.
* Blir [EventStream#type](https://gist.github.com/kjellm/ec8fbaac65a28d67f17d941cc454f0f1#file-event-rb-L12) brukt?
* Måtte vri hodet mitt litt for å få rett tankesett om hva `Command` her er VS `CommandHandler` (i Echo er Command det som utfører, mens Command her bærer data & validering  om noe man ønsker skal skje, som command handler mottar og utfører, som igjen resulterer i Events av ting som har skjedd).

**Comment by kjellm** [comment]
Takk for kommentarene :-)

> Inline docs av klassene og hva deres rolle/ansvar er kunne vært fint.

Ja, enig i det :-) Skal skrive det inn i bloggen når koden har satt seg.

> * Hvorfor har vi `InstanceMethods` og include modulen (eks `CommandHandler` med flere).
>   * Tror jeg fant [svaret](https://gist.github.com/kjellm/ec8fbaac65a28d67f17d941cc454f0f1#file-crud-rb-L50-L72).

Du fant svaret, ja. Er det andre måter å få til det samme på som er mindre forvirrende? Tenker uansett at konstruksjonen bør forklares i bloggen.

> Blir EventStream#type brukt?

Ikke foreløpig ... tenkte vel at det er nyttig metadata å ha? Skal tenke mer på det ...

> Hvordan håndtere Index-er: Garantere unike verdier ut over ID. Kanskje en annen konstruksjon får det ansvaret.

Hvis man rendyrker event sourcing med aggregater, slik jeg har forstått det, så vil det ikke være mulig å håndtere dette (pga aggregatene er skal være komplette med tanke på transaksjoner og eventual consistency greier). Så jeg tenker det blir litt utenfor denne diskusjonen. Kanskje en oppfølgingsblogg :-) Tenker at vi har en gangske grei løsning for dette i Echo, men at vi kanskje bør tenke litt igjennom om vi egentlig trenger den i de fleste tilfeller. Embrace eventual consistency ...

> Måtte vri hodet mitt litt for å få rett tankesett om hva Command her er VS CommandHandler (i Echo er Command det som utfører, mens Command her bærer data & validering om noe man ønsker skal skje, som command handler mottar og utfører, som igjen resulterer i Events av ting som har skjedd).

Ja, har også drevet og vrid hodet mitt i det siste :-P Navningen jeg bruker her ser ut til å passe bedre overens med de kildene jeg har funnet om CQRS og ES+A

Når det er sagt er det ikke nødvendigvis slik at jeg foreslår at vi endrer i Echo også. Blir litt avveining. Vi har jo litt andre forskjeller også i Echo. F.eks at her skal en CommandHandler bare opperere på én Aggregat-instans, mens i Echo har vi ingen slik begrensning på Command-ene.
